logger:
  level: DEBUG

input:
  label: "postgres_cdc"
  postgres_cdc:
    dsn: "postgres://iam_demo_user@demo-aurora-pg.cluster-cz84a4eu2syk.us-east-2.rds.amazonaws.com:5432/demo_db?sslmode=require"
    include_transaction_markers: false
    slot_name: "rpcn_iam_test"
    snapshot_batch_size: 1
    checkpoint_limit: 1
    stream_snapshot: false
    temporary_slot: true
    unchanged_toast_value: null
    schema: public
    tables:
      - "iamuser_test"

    tls:
      # for a quick dev test – *don’t* leave this in production:
      skip_cert_verify: true

    aws:
      enabled: true
      region: "us-east-2"

      endpoint: "demo-aurora-pg.cluster-cz84a4eu2syk.us-east-2.rds.amazonaws.com:5432"
      roles:
        - role: "arn:aws:iam::<Aurora AWS Acct ID>:role/rpcn-demo-xaccount-rds-connect-role"

pipeline:
  processors:
    - mapping: |
        root = this
        root._pg_meta = {
          "table": meta("table"),
          "operation": meta("operation"),
          "lsn": meta("lsn")
        }

output:
  kafka_franz:
    seed_brokers:
      - ${REDPANDA_BROKERS}

    topic: iam_test

    tls:
      enabled: true

    sasl:
      - mechanism: SCRAM-SHA-256
        username: ${secrets.CNELSON_SASL_USER}
        password: ${secrets.CNELSON_SASL_PASSWORD}
