input:
  kafka_franz:
    seed_brokers:
      - localhost:19092
    topics:
      - content_notification
    consumer_group: "sink_to_pg"

pipeline:
  processors:
    - log:
        message: '${! content() }'

output:
  sql_insert:
    driver: postgres
    dsn: postgres://admin:admin@localhost:5432/inventory?sslmode=disable
    table: public.content_notification
    columns:
      - event_id
      - destination_system
      - notification_type
      - status
      - duration

    args_mapping:
      root = [this.event_id, 
              this.destination_system, 
              this.notification_type, 
              this.status, 
              this.duration ]

    batching:
      count: 10
      period: 5s
